### ISSUE TITLE
Enable the Multibeam Bathymetry Tool for SonTek ADCPs

### ISSUE THREAD

**Issue by frank-engel-usgs** [frank-engel-usgs/VMT#9]
VMT user Chad Wagner reports the following errors when trying to process M9 data through the VMT-->Export Multibeam Bathymetry tool:

I am trying to output multi-beam bathymetry for a longitudinal transect collected in a creek for a study. However, when I try to output the bathymetry data in VMT, I get the errors shown below. Also, the error logs are not be created in the directory that is specified. I can't find that they are being created at all. I have tried with other M9 datasets and am getting the same errors. I would appreciate any assistance you can provide. 

![image](https://user-images.githubusercontent.com/7658425/33324185-8117a932-d414-11e7-9ea8-c3fcbffd546f.png)

**Comment by frank-engel-usgs** [comment]
The MBB tool (AdMap) implemented in VMT only supports TRDI ADCPs fully at this time. This is a feature request.

**Comment by RCardot** [comment]
Dear all,
Regarding the Multibeam Bathymetry using the SonTek M9, I would like to suggest one point, which should be included:
The Sontek M9 uses two set of transducers (1 MHz and 3 MHz), which are '45°-shifted'.
Then, while importing the M9 data from the Sontek MAT-file, the information about which frequency is used for each sample should be kept (BottomTrack.BT_Frequency). To my knowledge, it is not yet the case.
Once we got this, we can probably use the depth measured along each beam (BottomTrack.BT_Beam_Depth) and the transformation matrix corresponding to the used frequency (Transformation_Matrices) in order to determine where, in the ENU reference system, is located the ping which reached the bed. 
Unfortunately, I am not yet at ease with the spatial transformations using this matrices. 
I hope this is clear enough and can help. And by the way I will be happy to help on any point to progress regarding this feature request.
Romain

**Comment by frank-engel-usgs** [comment]
I have incorporated the changes into a new function `depthxyzRS` that is called if the user loads SonTek Mat-files. This new version of `utils\depthxyzRS' accounts for the change in beam orientation by 45­­­° depending on whether the 1 or 3 kHz beams is in use. It also processes the vertical beam data and retains that.  The output now retains all 4 slant beam elevations, as well as the vertical beam where valid. For example, you can look at ensemble 221 and see 5 entries: beams 1,2,3,4, and the vertical beam. 
![image](https://user-images.githubusercontent.com/7658425/33456837-37d8133c-d5e6-11e7-8fef-82e125b6a2a8.png)

Note that the user will need to set the the correct beam angle for the ADCP used:
![image](https://user-images.githubusercontent.com/7658425/33456900-74289cee-d5e6-11e7-83c6-0935fcde7540.png)
In the case of SonTek M9, that's 25°
![image](https://user-images.githubusercontent.com/7658425/33456927-87d952ba-d5e6-11e7-9de6-644d4f3e1c9e.png)

VMT will create an error dialog if it recognizes that M9/S5 data are loaded and the beam angle is wrong. 

To make this functionality work, I had to go back and change how SonTek data are loaded. As a result, now the A.Nav.depth outputs will include 5 columns, with the last being the vertical beam if a SonTek probe is loaded (the first 4 columns are the 4 _active_ slant beams, regardless of frequency).

I did not address loading SonTek data with the VMT Batch Tool- this is a larger feature request that can be tackled later.

**Comment by frank-engel-usgs** [comment]
Going to add functionality to incorporate the `auxmat` data into the VMY_MBBathy function.

**Comment by frank-engel-usgs** [comment]
I have added this functionality. This feature request is now complete. Closing issue.
